In [1]:
my_list = [1,2,3
          ]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np


In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros(5,5)

TypeError: Cannot interpret '5' as a data type

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((2,100))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((50,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(2)

array([0.45941669, 0.08058531])

In [30]:
np.random.rand(5)

array([0.01633352, 0.42960635, 0.34185662, 0.99917538, 0.16601859])

In [32]:
np.random.rand(3,4)



array([[0.91293053, 0.50665985, 0.30541039, 0.92519375],
       [0.52502149, 0.04273188, 0.78535852, 0.1843575 ],
       [0.91946179, 0.57168566, 0.92900255, 0.03968371]])

In [33]:
np.random.randn(2)

array([0.30689182, 0.30880224])

In [34]:
np.random.randn(3)

array([-1.69647038,  1.29085209, -0.47818448])

In [35]:
np.random.randn(5,4)

array([[ 0.8640822 , -1.98806788, -0.78926141,  0.97096076],
       [ 0.31070146,  1.89972806, -2.27102131, -0.01874103],
       [-0.6504503 , -1.25696256, -0.65122662,  2.31443615],
       [ 0.10689587, -0.03325228,  0.19065358, -0.3520064 ],
       [-0.83116651,  1.21404567, -0.00526794,  0.6006416 ]])

In [36]:
np.random.randint(1,5)

1

In [37]:
np.random.randint(1,100)

89

In [40]:
np.random.randint(1,100,(15,2))

array([[38, 30],
       [46, 14],
       [55, 22],
       [87, 24],
       [69, 44],
       [ 3, 15],
       [44,  8],
       [96, 25],
       [79, 67],
       [72, 53],
       [36, 37],
       [53, 93],
       [12, 76],
       [33, 18],
       [60, 64]])

In [44]:
arr = np.arange(25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr = np.random.randint(0,50,10)

In [47]:
ranarr

array([38,  3, 21,  4, 36, 26, 26, 38, 23, 32])

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr

array([38,  3, 21,  4, 36, 26, 26, 38, 23, 32])

In [50]:
ranarr.max()

38

In [51]:
ranarr.min()

3

In [52]:
ranarr.mean()

24.7

In [55]:
ranarr.argmax()

0

In [56]:
ranarr.argmin()

1

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
arr.shape

(25,)

In [59]:
arr = arr.reshape(5,5)

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr.shape

(5, 5)

In [62]:
arr.dtype

dtype('int64')

In [63]:
ranarr.dtype

dtype('int64')

In [64]:
from numpy.random import randint

In [65]:
randint(20,2)

ValueError: low >= high

In [66]:
randint(20,40)

36

In [68]:
randint(0,40,20)

array([37, 31, 15, 37, 19, 27,  7, 24, 32, 34, 19,  7, 32, 36, 34, 21,  9,
        2, 14,  4])

In [71]:
randint(0,40,20).reshape(4,5)

array([[30, 22, 16, 26, 34],
       [14, 31, 38, 28, 16],
       [36,  4, 23, 39, 18],
       [16, 38, 22, 28, 14]])

In [72]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[8]

8

In [76]:
arr[10]

10

In [77]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [78]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [79]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [81]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [83]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [84]:
arr[0:5] = 100

In [85]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [86]:
arr = np.arange(0,11)

In [87]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
slice_of_arr = arr[0:6]

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [91]:
slice_of_arr[:] = 99

In [92]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [93]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
arr_copy = arr.copy()

In [95]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [96]:
arr[:] = 100

In [97]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [98]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [99]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [100]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [101]:
arr_2d[0][0]

5

In [102]:
arr_2d[0
      ]

array([ 5, 10, 15])

In [103]:
arr_2d[1][2]

30

In [104]:
arr_2d[2][1]

40

In [105]:
arr_2d[2,1]

40

In [106]:
arr_2d[1,2] #single bracket recommended due to being less prone to error

30

In [107]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [108]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [110]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [111]:
arr_2d[1]

array([20, 25, 30])

In [112]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [113]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [114]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [115]:
arr_2d.append([50,55,60])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [116]:
arr_2d + [50, 55,60]

array([[ 55,  65,  75],
       [ 70,  80,  90],
       [ 85,  95, 105]])

In [117]:
arr= np.arange(1,11)

In [118]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [120]:
[1,2,3,4] > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [125]:
bool_arr = arr > 5

In [126]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [127]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [128]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [129]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [130]:
arr[arr<3]

array([1, 2])

In [131]:
arr_2d = np.arange(50).reshape(5,10)

In [132]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [134]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [135]:
arr_2d[1,:5]

array([10, 11, 12, 13, 14])

In [136]:
arr_2d[arr_2d<25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [137]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [138]:
arr_2d[:,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [139]:
arr_2d[2:4,5:7]

array([[25, 26],
       [35, 36]])

In [140]:
arr_2d[2:4,4:9]

array([[24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38]])

In [141]:
arr_2d[3,2]

32

In [143]:
arr_2d[3,6]

36

In [144]:
arr_2d[2:,3:5]

array([[23, 24],
       [33, 34],
       [43, 44]])

In [150]:
for y in range(len(arr_2d[0])):
    for x in range(len(arr_2d)):
        print (arr_2d[x,y], end = ' ')
    print()

0 10 20 30 40 
1 11 21 31 41 
2 12 22 32 42 
3 13 23 33 43 
4 14 24 34 44 
5 15 25 35 45 
6 16 26 36 46 
7 17 27 37 47 
8 18 28 38 48 
9 19 29 39 49 


In [148]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [151]:
for x in range (len(arr_2d)):
    for y in range(len(arr_2d[0])):
        print (arr_2d[x,y], end = ' ')
    print()

0 1 2 3 4 5 6 7 8 9 
10 11 12 13 14 15 16 17 18 19 
20 21 22 23 24 25 26 27 28 29 
30 31 32 33 34 35 36 37 38 39 
40 41 42 43 44 45 46 47 48 49 
